stages: ["build", "deploy"]

build:
  type:  build
  image: registry.code.go1.com.au/go1/docker:golang
  tags: ["aws"]
  artifacts: { paths: ["artifacts"] }
  services:
    - rabbitmq:3.6-alpine
  variables:
    RABBITMQ_DEFAULT_USER: "go1"
    RABBITMQ_DEFAULT_PASS: "go1"
    GOOS:                  "linux"
    GOARCH:                "386"
    GO111MODULE:           "on"
    QUEUE_URL:             "amqp://go1:go1@rabbitmq:5672"
  before_script:
    - curl -sSL -o wait-for-it.sh https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
    - chmod +x ./wait-for-it.sh
  script:
    - go mod vendor
    - go test
    - go build -o $CI_PROJECT_DIR/artifacts/app cmd/main.go
